# Generated by Django 4.0.5 on 2022-06-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidates',
            options={'managed': False, 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='candidatesold',
            options={'managed': False, 'verbose_name': 'Old Candidate', 'verbose_name_plural': 'Old Candidates'},
        ),
        migrations.AlterModelOptions(
            name='homelanguages',
            options={'managed': False, 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='matricschools',
            options={'managed': False, 'verbose_name': 'Matric School', 'verbose_name_plural': 'Matric Schools'},
        ),
        migrations.AlterModelOptions(
            name='matricsubjects',
            options={'managed': False, 'verbose_name': 'Matric Subject', 'verbose_name_plural': 'Matric Subjects'},
        ),
        migrations.AlterModelOptions(
            name='postgradqualifications',
            options={'managed': False, 'verbose_name': 'Post-Grad Qualification', 'verbose_name_plural': 'Post-Grad Qualifications'},
        ),
        migrations.AlterModelOptions(
            name='postgraduniversities',
            options={'managed': False, 'verbose_name': 'Post-Grad University', 'verbose_name_plural': 'Post-Grad Universities'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'managed': False, 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='trainingelectives',
            options={'managed': False, 'verbose_name': 'Training Elective', 'verbose_name_plural': 'Training Electives'},
        ),
        migrations.AlterModelOptions(
            name='undergradqualifications',
            options={'managed': False, 'verbose_name': 'Under-Grad Qualification', 'verbose_name_plural': 'Under-Grad Qualifications'},
        ),
        migrations.AlterModelOptions(
            name='undergraduniversities',
            options={'managed': False, 'verbose_name': 'Under-Grad University', 'verbose_name_plural': 'Under-Grad Universities'},
        ),
    ]
