# Generated by Django 4.0.5 on 2022-06-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_candidates_options_alter_candidatesold_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
